services:
  postgres:
    container_name: postgres-spring-mvc-1
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: springmvc
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-mvc
    restart: unless-stopped

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:24.0.4
    ports:
      - "8181:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - spring-mvc
    command:
      - "start-dev"

networks:
  spring-mvc:
    driver: bridge

volumes:
  postgres:
    driver: local
  keycloak:
    driver: local